services:
  api:
    environment:
      - NODE_ENV=${NODE_ENV}
    env_file:
      - .env
    build:
      context: .
      target: "${NODE_ENV}"
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    restart: unless-stopped
    depends_on:
      - bd
    networks:
      - payment-network
  bd:
    image: postgres:latest
    env_file:
      - .env
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: "${POSTGRES_DATABASE}"
      PG_DATA: /var/lib/postgresql/data
    # volumes:
    #   - postgres-data:/var/lib/postgresql/data
    networks:
      - payment-network

volumes:
  postgres-data:

networks:
  payment-network:
    name: "payment-network"